local   all             postgres                                peer
local   all             all                                     scram-sha-256
hostssl janus_control   janus_control      10.42.0.0/24          scram-sha-256
hostssl janus_control   janus_catalog      10.42.0.0/24          scram-sha-256
hostssl janus_control   janus_publication  10.42.0.0/24          scram-sha-256
hostssl janus_control   janus_audit        10.42.0.0/24          scram-sha-256
hostssl janus_control   janus_web_control  10.42.0.0/24          scram-sha-256
hostssl janus_control   janus_web_catalog  10.42.0.0/24          scram-sha-256
host    all             all                0.0.0.0/0             reject
